### ISSUE TITLE
Using p2 repo in tycho build fails

### ISSUE THREAD

**Issue by hannesN** [OLibutzki/xtext.tools#11]
There seems to be a problem with the SSL certificate:
[ERROR] Failed to resolve target definition [...] Failed to load p2 metadata repository from location https://xtexttools.libutzki.de/: Unable to read repository at https://xtexttools.libutzki.de/content.xml. sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]

**Comment by hannesN** [comment]
Eclipse seems to have no problem with the URL.

**Comment by OLibutzki** [comment]
Hmm, it's a Let's encrpyt certificate which my browser's calssify as being valid...

Maybe your Java runtime does not trust certificates issued by Let's Encrpyt?

**Comment by hannesN** [comment]
Hm weird, I have 1.8.0_241. I will investigate.

**Comment by OLibutzki** [comment]
Any news?

**Comment by hannesN** [comment]
Well I hadn't have time but a collegue of mine tested it and it worked, so I guess it's a problem on my machine. Can be closed.

**Comment by OLibutzki** [comment]
Thanks for providing feedback.
