### ISSUE TITLE
unable to access 'https://xtexttools.libutzki.de/'

### ISSUE THREAD

**Issue by wchaoRealize** [OLibutzki/xtext.tools#14]
when I try to install in eclipse, it shows that 'Unable to read repository at https://xtexttools.libutzki.de/.
https://xtexttools.libutzki.de/ is not a valid repository location.'
Is this site okay now?

**Comment by OLibutzki** [comment]
The update site works for me.

**Comment by wchaoRealize** [comment]
> 
Thanks for your reply. I changed the certificate settings and tried again successfully.
