### ISSUE TITLE
Updatesite not working

### ISSUE THREAD

**Issue by hannesN** [OLibutzki/xtext.tools#7]
The given update site is not working anymore. (for at least a week now).

**Comment by OLibutzki** [comment]
Thanks for the hint. I will investigate it.

**Comment by protoben** [comment]
+1

I'm trying to build a project that wants to pull the xtext.tools Eclipse plugin, but http://xtexttools.libutzki.de/ is down. Would be great if this could get resolved.

Thanks!

**Comment by Julia-Tomsk** [comment]
I'm also using the plugin and the Semantic Model Outline viewer, would be great to have the update site available again. Many thanks!

**Comment by OLibutzki** [comment]
First of all I need to fix the build. Hopefully, I will find some time soon...

**Comment by hannesN** [comment]
I fixed the build and opened a pull request. I hope this helps to speed up the work a bit.

**Comment by OLibutzki** [comment]
Thanks @hannesN,

I merged your #8. 

Next step is to find out how where to host the p2 repo as the "old web server" doesn't exist anymore. I would like to use GitHub Actions to automate this stuff...

**Comment by OLibutzki** [comment]
For the time being the updatesite should be back.

I automated the process using GitHub Actions and pushed it to GitHub Pages. Seems to work nicely in the first place. Anyway I have to polish the solution in a seperate issue.

The updatesite is available via https://xtexttools.libutzki.de. It's **https** now.

Please test and give feedback.

**Comment by hannesN** [comment]
Looks good. Works for me. Maybe you should add an UPDATE-section on top of the readme.md so everybody knows the http has changes :)

**Comment by OLibutzki** [comment]
http should work as well bad it's forwarded to https.
